workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      groups:
        - google_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FIREBASE_PROJECT: "attendance-6dcd9"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --debug
      - name: Create debug and test APK
        script: |
          set -ex
          cd android
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/integration_test/admin_test.dart"
          ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/integration_test/check_page_test.dart"
          ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/integration_test/list_test.dart"
          ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/integration_test/res_test.dart"
          ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/integration_test/reservation_parking_test.dart"
          ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/integration_test/view_reservation_test.dart"
      - name: Run Firebase Test Lab Tests
        script: |
          set -ex
          echo $GCLOUD_KEY_FILE | base64 --decode > ./gcloud_key_file.json
          gcloud auth activate-service-account --key-file=gcloud_key_file.json
          gcloud --quiet config set project $FIREBASE_PROJECT
          
          gcloud firebase test android run \
            --type instrumentation \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device-ids=blueline,OnePlus5T,x1q,redfin,flame \
            --os-version-ids=25,26,27,28,29,30 \
            --locales=en_GB,es \
            --orientations=portrait,landscape \
            --use-orchestrator \
            --timeout 3m \
            --results-bucket=gs://integration_results_attendance \
            --results-dir=tests/firebase
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log