name: 'ARRK'
description: This project is created for the ARRK employees.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  image: ^4.0.17
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  cloud_functions: ^4.3.4
  intl: ^0.18.1
  uuid: ^3.0.7
  file_picker: ^5.3.2
  excel: 2.1.0
  path_provider: ^2.1.0
  path: ^1.8.3
  firebase_storage: ^11.2.6
  http: ^1.1.2
  #flutter_microsoft_authentication: ^0.1.1
  #provider: ^6.0.5
  internet_connectivity_checker: ^1.0.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  firebase_core: ^2.14.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

