name: 'ARRK'
description: This project is created for the ARRK employees.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  image: ^4.0.17
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  cloud_functions: ^5.1.3
  intl: ^0.19.0
  uuid: ^4.5.1
  file_picker: ^8.1.2
  excel: ^4.0.6
  path_provider: ^2.1.0
  path: ^1.8.3
  firebase_storage: ^12.3.2
  http: ^1.1.2
  internet_connectivity_checker: ^1.0.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  image_picker: ^1.0.4
  camera: ^0.11.0+2
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

