// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmPZjva9oNg1jy96STW9SLXxRHVxUNE8Y',
    appId: '1:93250576938:web:d59e34ca69d2d600ca9953',
    messagingSenderId: '93250576938',
    projectId: 'attendance-6dcd9',
    authDomain: 'attendance-6dcd9.firebaseapp.com',
    storageBucket: 'attendance-6dcd9.appspot.com',
    measurementId: 'G-HSQZGL0CH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-0OpZXOblxrcZPcJ0743e3WZdIeHph_k',
    appId: '1:93250576938:android:2e206cf66ce86918ca9953',
    messagingSenderId: '93250576938',
    projectId: 'attendance-6dcd9',
    storageBucket: 'attendance-6dcd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkmkVbtz_qhjVcZ2zA27b8JiLFB3RhEN4',
    appId: '1:93250576938:ios:69d82621e493832eca9953',
    messagingSenderId: '93250576938',
    projectId: 'attendance-6dcd9',
    storageBucket: 'attendance-6dcd9.appspot.com',
    iosBundleId: 'com.example.attendanceSystemSzabi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkmkVbtz_qhjVcZ2zA27b8JiLFB3RhEN4',
    appId: '1:93250576938:ios:69d82621e493832eca9953',
    messagingSenderId: '93250576938',
    projectId: 'attendance-6dcd9',
    storageBucket: 'attendance-6dcd9.appspot.com',
    iosBundleId: 'com.example.attendanceSystemSzabi',
  );
}
