import 'package:ARRK/constants/constants.dart';
import 'package:flutter/material.dart';
import '../models/manager.dart';
import '../services/manager_firebase_service.dart';

class AddManagerScreen extends StatefulWidget {
  const AddManagerScreen({super.key});

  @override
  AddManagerScreenState createState() => AddManagerScreenState();
}

class AddManagerScreenState extends State<AddManagerScreen> {
  final TextEditingController _nameController = TextEditingController();
  String _statusName='';
  bool _isValid=false;

  @override
  void initState() {
    super.initState();
  }


  Future<void> _addManager() async {
    String nameGiven = _nameController.text;

    if (nameGiven =='') {
      setState(() {
        _statusName= 'Enter a name in the textfield!';
        _isValid=false;
      });
    } else {
      Manager? manager =
      await ManagerFirebaseService.getManagerByName(nameGiven);
      if (manager == null) {
        Manager newManager = Manager(
          id: '', // Leave the ID empty since it will be generated by Firestore
          name: nameGiven,
          nrOfEmployees: 0,
        );
        await ManagerFirebaseService.addManager(newManager);
        setState(() {
          _statusName="Added with succes.";
          _isValid=true;
        });
        // Wait for 2 seconds before popping the screen
        Future.delayed(const Duration(seconds: 2), () {
          Navigator.of(context).pop();
        });
      } else {
        setState(() {
          _statusName =
              'Name is already in use for the manager: $_statusName';
          _isValid=false;
        });
      }
    }
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Manager'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              TextField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Name'),
              ),
              Text(
                _statusName,
                style: TextStyle(color: _isValid==true?AppColors.kGreen600Color: AppColors.kRed800Color),
              ),
              ElevatedButton(
                onPressed: _addManager,
                child: const Text('Add'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
